### ISSUE TITLE
New versions of Chisel blocks cannot be cut into Microblocks

### ISSUE THREAD

**Issue by Jadziyah** [Yulife/Wanderlust-Reloaded#120]
In WLR 1.1.2, some of the blocks from Chisel were able to be cut into Microblocks (Forge). Now in the 1.1.3 update the Chisel mod has changed some of their block names which causes a disconnect between Chisel and Forge Microblocks - blocks that were previously cuttable are now not able to be microblocked (yes, that's totally a verb). For instance: smooth stone, block of iron, dirt, etc. Our sexy Head Admin attempted to rematch the names of blocks, but that causes a huge list of rejections when attempting to join the server. 

![image](https://cloud.githubusercontent.com/assets/9683937/5001849/44cc4ca8-69c8-11e4-8ff4-ef6d0e657684.png)

Thanks!

**Comment by Yulife** [comment]
[There ya go](https://twitter.com/Drullkus/status/555258373742944256), lovely @Jadziyah.
