### ISSUE TITLE
Elemental Crop Potions cannot be crafted

### ISSUE THREAD

**Issue by Yulife** [Yulife/Wanderlust-Reloaded#150]

**Comment by Yulife** [comment]
@pixlepix and @nekosune apparently those potions aren't craftable. Is it reported yet?

**Comment by belathus** [comment]
This was reported: https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/issues/671

**Comment by nekosune** [comment]
It helps rather then asking in an unrelated issue tracker if it has been reported, either use the search function or report it yourself :) much more visible

**Comment by belathus** [comment]
I managed to fix this using a Modtweaker script in 2.0.0.
