### ISSUE TITLE
Cardboard boxes should be disabled.

### ISSUE THREAD

**Issue by Gadgetinator** [Yulife/Wanderlust-Reloaded#159]
I believe that cardboard boxes should be disabled, or at the very least operate on a whitelist for several reasons.

First, they are incredibly cheap for the uses they have. Using a cardboard box and chests, it is possible to have infinite inventory space easily, move spawners, and allow silk touch for grass.

Second, they can cause crashes for multiple reasons. Aura nodes, beds, and multi blocks can occasionally crash when placed with cardboard boxes.

Third, they allow effortless circumvention of all Thaumcraft warded items, including the arcane door, items warded with the focus, and the actual warded items.

For these reasons, and others not explicitly stated, I believe that cardboard boxes should be disabled or moved to a whitelist functionality in 1.1.4

**Comment by Yulife** [comment]
Moved to https://github.com/Yulife/Wanderlust-Reloaded/issues/375
