### ISSUE TITLE
Wanderlust Reloaded 2.x | The world devouring update | Suggestions | Discussion | 

### ISSUE THREAD

**Issue by Yulife** [Yulife/Wanderlust-Reloaded#216]
The official discussion place for even prior 2.x releases but in particular this far away version. Post your opinion here, whether it is in your current situation or in the future one.
Feel free to suggest mods, scripts, etc.

**Additions:**
-NotEnoughResources
-~~NEIIntegration~~
-SoundMuffler
-~~OpenPeripherals~~
-~~Steve's Addon~~
-Ruins
-AncientTrees
-ATG (optional)
-Redstonic Drills
-NotEnoughKeys
-CustomMainBackround
-Resource Loader
-BuildcraftComp

**Removals:**
-Nearby Mod Finder
-Binnie's Fix (Cloudy)
-WTP
-Bluepower
-NEIPlugins
-RPGAdvanced
-TheKitchenMod
-WTP
-Fluxed Trinkets
-FLORA

**Changes:**
-Forestry Questline
-New assets (Backround, GUIs)
-Make AM2 Optional

-----------------------------------------------------------------------------------------------------------------------------------------

**Mods that won't get added:**
-Technomancy
-Reika's
-Optifine
-Modular Powersuits
-Minechem
-Veinminer
-CompactMachines
-Spice of Life
-Passive Energy Generation Mods (SolarFlux, Advanced Solar, etc..)
-Chococraft
-Galacticcraft
-Gendustry

**Comment by Yulife** [comment]
I am thinking about removing Statues. Hardly I see it being used anywhere nowadays and it is just another mod that adds one feature for the cost of precious, sweet performance. Give me your opinions!

**Comment by Woif1990** [comment]
Ember: "Fuck off" on removing statues.

**Comment by Yulife** [comment]
Not sure if agreement or disagreement.

**Comment by penguinsane** [comment]
I like Statues and use them fairly frequently. It's sort of one of those mods where in moderation, it's nice. If someone wants to bloat their base with them... well, that's their prerogative, but a few statues here or there doesn't hurt much. There are plenty of other mods in the pack where performance is an issue once you use tons of it, so it's not an exclusive issue.

**Comment by Yulife** [comment]
I see. Will keep it then :)

**Comment by Woif1990** [comment]
Ember was telling you to fuck off and not the statues ;P but I'm sure
she'll change her mind since you're keeping it

**Comment by Yulife** [comment]
Ember is one evil lady :P

**Comment by Yulife** [comment]
Feel free to drop in the discussion in https://github.com/Yulife/Wanderlust-Reloaded/issues/375

**Comment by penguinsane** [comment]
Mod suggestion: FlatSigns (http://www.curse.com/mc-mods/minecraft/flatsigns)

Can put signs flat on the ground/ceiling, which is a function I miss quite often. Can also edit current signs with sponges.

**Comment by Yulife** [comment]
Sorry, not a fan of it :( It is also not compatible with Tinkers' and Bibliocraft signs.

**Comment by penguinsane** [comment]
Not a fan of... signs on the ground? That's strangely specific, lol.

What about Easy Crafting? http://www.curse.com/mc-mods/minecraft/224295-easycrafting

It's like the old Project Table? from early Tekkit days, gives you a list of craftable things from the items in your inventory. Would be really handy in the early game.

**Comment by Yulife** [comment]
Oh god, I adore that mod to heaven. We had it in WLR before it published. Crashed servers constantly. It is too good to be true, it seems.

**Comment by penguinsane** [comment]
Bummer! Did you happen to report your issues to the mod author? Maybe if they're active, they may be willing to fix whatever issues there were.

**Comment by Yulife** [comment]
Has it updated? lol

**Comment by penguinsane** [comment]
No, but the only comment at least on Curse regarding server stability was back in September, and the author hasn't replied to anything on Curse or Curseforge, so I guess it's just dead in the water. Bleh, was worth a shot!

**Comment by Yulife** [comment]
I love the mod.. I understand ya ;(

**Comment by tomaste** [comment]
This sounds like fun!  http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1288630-plunder-rummage-forge-10-2-13-1230-treasure

**Comment by penguinsane** [comment]
Plunder Rummage is a fun mod. I messed with it back in super early 1.6 on a custom pack, it was neat.

A handful of other suggestions. I haven't tested these, not 100% sure of their stability,but they might fit the RPG/fantasy/exploration theme. I double checked their modpack permissions, and they're good to go (except Lost Books, the modpack permissions aren't elaborated) as long as they're not monetized and are credited. 

Minecraft Comes Alive (villages more lively, can marry/have kids in SMP): http://www.curse.com/mc-mods/minecraft/mca
MAtmos (additional sounds and atmosphere): http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1274487-matmos-r26-environmental-sound-atmosphere?comment=3582
Adventure Backpacks (fleshed out backpacks, can carry liquids, etc): http://www.curse.com/mc-mods/minecraft/225063-adventure-backpack
Luppii's Ladders (drawbridge-like ladders): http://www.curse.com/mc-mods/minecraft/luppiis-ladders
Ztones (additional aesthetic blocks, but mostly fairly modern): http://www.curse.com/mc-mods/minecraft/224369-ztones
Realistic World Generation (instead of ATG, has BoP support): http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1281910-teds-world-gen-mods-rwg-owg-bwg4
Lost Books (heavily customizable, can add lore to WLR if that's your thing): http://www.curse.com/mc-mods/minecraft/lost-books

**Comment by number5** [comment]
Maybe should consider remove some mods?

Some of them are really buggy and resource demanding and not much use, e.g.
UE series
RemoteIO
SuperMassiveTech

(Railcraft too but I get why you can't remove it...)

**Comment by penguinsane** [comment]
I know it was said in IRC at the time, but I'm pretty sure a lottttttttt of people would riot if Railcraft were removed, lol. :)

Inap, what about Gendustry? I saw it had a 1.7.10 version. I didn't see it in the "Will Not Add" pile and it's pretty darn popular. Saves some time re: mutations at the cost of quite a bit of power and resources, but I suppose it overlaps with Binnie's Mods quite a bit. Shoot, it could probably be responsible for a bunch of quests, too. If you have plans for a Forestry questline, I can't wait to see it. :)

**Comment by Torins** [comment]
Actually, there was once a request to add Gendustry and it was denied: #38

In case of mutations, I'm afraid Gendustry will invalidate parts of Binnie's Mods, not just overlap with it
Gendustry's mutation system is much simpler (and faster) than BM's.

Besides mutations though, Gendustry also offers a mechanical apiary with upgrades and a system of defining custom bees in json, which you may or may not be interested in.

Perhaps gendustry could be added, but parts of it disabled? Yulife, do you not like the mod as a whole, or just parts of it?

**Comment by Yulife** [comment]
Yeah... I hate the mod in essence. It just makes bee breeding easy and that kills the point of initial bee breeding. Patience and thinking about how thinks will mutate.

**Comment by Torins** [comment]
I kinda agree. Last time I delved deep into bee breeding was before gendustry, heck, before magic bees were a thing. It felt rewarding to create "the perfect bee" using ExtraBees (BM's name back then) mechanics.

Yulife, have you considered adding gendustry without mutations though?
You will still add an [Industrial Apiary](http://bdew.net/gendustry/industrial-apiary/) with various [upgrades](http://bdew.net/gendustry/industrial-apiary/upgrades/), an upgraded [grafter](http://bdew.net/gendustry/industrial-grafter/) and [scoop](http://bdew.net/gendustry/industrial-scoop/).
You will also be able to add [custom bees](http://bdew.net/gendustry/configuration/adding-custom-bees/) that produce whatever you wish.

**Comment by Yulife** [comment]
Sorry, I want to keep mods  to a limit right now.

**Comment by Torins** [comment]
No worries, it was just a suggestion. You're doing a great work nevertheless.

**Comment by cHaOZZoNE** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292114-cakeisalie-mod-1-7-10-in-update

Because who doesnt like more Kuchen

**Comment by ChaseCarlton** [comment]
Have you considered Revamp? Updates passive mob and villager AI. It might make the villagers actually able to survive a blood moon. 

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287045-revamp-rivvests-enhanced-villagers-and-mob

**Comment by Bob41599** [comment]
Can we do some work with reward bags atm they feel kinda stale like I don't feel like i'm being rewarded just getting a bunch of useless stuff to find room for.

**Comment by Yulife** [comment]
The point of reward bags is to give you basic materials, not something that you would get through getting far into a mod.

**Comment by Bob41599** [comment]
What if you did stuff that wouldn't break it but add interest like tinkers
tools or me drives

**Comment by Yulife** [comment]
Did you read what I said? No progression rewards but basic ones.

**Comment by gukliuyk** [comment]
getting a milion basic capacitors and redstone engines doesnt make it feel like you are rewarded for your progression <,<

**Comment by Yulife** [comment]
WLR is one of the few packs that has a reward system. Most packs are balanced to not even give rewards. I think rewards should be modest, not something that helps quickly & actively like in, for example, Agrarian Skies.

**Comment by gukliuyk** [comment]
Whats your opinion on something like heartcanisters, caches filled with a single mainly useless like snowballs ressource, specific mobheads/skulls, single pieces of multiblocks, highly progressed bee with terrible stats, florbs of random liquids, more renamed spawneggs(you know the frostyfu***r thing im talking about) and carpenter building blocks?

**Comment by exops91** [comment]
Well I will say yulife one of you rewards took me a bit to cut down lol man those rubber trees that are mega ones are a pain in the a** to cut down lol got loads of rubber now though lol 

What I would say is in the reward bags some are good but others need tinkering as the coloured clay to me is not that good as I just trash can them is say for some rewards make some ore bushes and stuff like that so then it adds more randomness to them :)

**Comment by Yulife** [comment]
Ore Bushes have already been added. Hardened Clay is often used by many people, including me.

**Comment by exops91** [comment]
yea i finally got some in my bags now lol i will say with the rpg aspect of it for the 2.0.0 could train craft be added as i do enjoy the mod a lot as i can make rail systems more realistic but also i had it on a server where we all were pulling together to make a working rail system with traincraft trains where players would gather items then transport them via there trains to a player market which i found cool but this could be also doable in single player as people could have bases scattered over the place btu could make a system where they can drive the trains to each one themselves also there is a blimp in it which the recipe could be tweaked a bit to then have a way of flying without a jetpack at the cost of coal 

also theres the small boats mod which adds more boats to tie in with mariculture as i find that mods just there by itself and the boats have there own chest in them so its good for early game sea exploration :D

**Comment by 016Nojr** [comment]
Traincraft is love <3 Traincraft is life! <3

**Comment by Yulife** [comment]
Ehhhh, Belathus needs to keep mod additions at a minimum. If a mod already adds it (Railcraft) it's redunant.

**Comment by Bob41599** [comment]
Is there any reason why you don't want to use fastcraft (if it's for not being allowed go check out his page this has been changed)

**Comment by Yulife** [comment]
2.0.0 should have it.
