### ISSUE TITLE
Request: Add Open Peripherals

### ISSUE THREAD

**Issue by mmmToast63** [Yulife/Wanderlust-Reloaded#255]
I'd really like to have Open Peripherals as a computercraft addon available. DW20 1.7 pack uses the following:

OpenPeripheralAddons-1.7.10-0.2.0-snapshot-122.jar
OpenPeripheralCore-1.7.10-0.5.0-snapshot-142.jar

Thanks.

**Comment by Chiisato** [comment]
Will this be added to the current version of the mod, or will we wait until 2.0?

**Comment by Yulife** [comment]
2.0.0.

**Comment by Chiisato** [comment]
Got it, i was confused by the 1.2.0 label. Do you have a sneak peak ETA when the 2.0.0 version will be released? ;3

**Comment by Yulife** [comment]
Nope!
