### ISSUE TITLE
Pulverizer/SAG-Mill support for Cinnibar

### ISSUE THREAD

**Issue by Yulife** [Yulife/Wanderlust-Reloaded#302]

**Comment by Bramcraft** [comment]
This is the recipe you gave me 100% chance of dropping 2 and a 30% chance of dropping 3

**Comment by Yulife** [comment]
I think I meant 3 Quicksilver drops.. (a nineth of a full Quicksilver) kekekeke ^^

**Comment by Yulife** [comment]
<Thaumcraft:ItemNugget:5>
their unlocalized name

**Comment by Yulife** [comment]
Let me see if I can do this... replaced the Resource with Nugget and placed the correct meta-data.

**Comment by Bramcraft** [comment]
Should be right! Did you get the hang of the poison the otherday?

**Comment by Yulife** [comment]
Haven't tried to implement it yet, checking through issues & pull requests atm.

**Comment by Yulife** [comment]
http://puu.sh/e6nk3/3a56167128.png
Alright, awesome :)

**Comment by Bramcraft** [comment]
Nice work! Just updating enderio and thermal to figure it out! Works fine on 1.2.0 versions of mods
