### ISSUE TITLE
Compatibility issue: TiCon Copper and Flaxbeards

### ISSUE THREAD

**Issue by Nocty201** [Yulife/Wanderlust-Reloaded#328]
Unverified on standard WLR SSP, but on MayhamSanctum copper ore smelts into TiCon ingots in a smeltery. Those TiCon ingots don't seem to be accepted by the Flaxbeard's crucible.

Crafting into blocks/nuggets and back doesn't seem to help.

Putting the ingots in an AE2 grindstone and grinding them to dust (IC2 copper dust) does seem to work.

Will test in WLR SSP and confirm later.

**Comment by NegativeNothing** [comment]
u could make a mariculture dictionary block, can change ore dictionary types back and forth.

**Comment by belathus** [comment]
Looks like this was fixed.
