### ISSUE TITLE
[1.1.0] Fertilized Dirt from RandomItems does not like Pam's type plants

### ISSUE THREAD

**Issue by per1970** [Yulife/Wanderlust-Reloaded#35]
Tried this with soybeans, lettuce and okra.

To reproduce:
-Put down a fertilized dirt block
-plant any of the above on it
-watch the seed pop out after just a short while (1-20 seconds)

Cacti, trees and cane works fine

**Comment by belathus** [comment]
Looks like Pam's fixed this. However, it is still a problem with Witchery crops, which I doubt'll get fixed.
