### ISSUE TITLE
Cardbox Blacklist Discussion

### ISSUE THREAD

**Issue by Yulife** [Yulife/Wanderlust-Reloaded#375]
If you feel like a block is not suitable or fitting getting moved by a Cardbox from Mekanism, post your thought of balance here.

Current ideas:
-Node (Thaumcraft 4)
-Energy Cluster (Hardcore Ender Expansion)
-Black Holes (Super Massive Tech)
-Demon Portal (Blood Magic)
-Transport Beacon (Hardcore Ender Expansion)

**Comment by Yulife** [comment]
Hey @chylex I already added energy clusters and the bacon, you think any other block in HEE is not appropriate to be taken with a cardbox?

**Comment by chylex** [comment]
All blocks that shouldn't be moved cannot be moved (clusters, beacons, spawners). They will either break or stop working. If that's not the case, let me know.

**Comment by BBoldt** [comment]
@chylex They just explode when you try to pick them up.


@Yulife Have you actually gotten the cardboard box blacklist to work? Using the same blacklist config in my pack doesn't yield that result. I'm using the latest Mek & Thaumcraft.

**Comment by belathus** [comment]
Buildcraft's oil and water springs. Thaumcraft's arcane door, arcane pressure plate, warded glass, warded blocks, Twilight Forest's mining core, and the anti-builder block.

However, I'm not even sure this blacklist works in 1.7.10.
