### ISSUE TITLE
Rising Dawn bugs.

### ISSUE THREAD

**Issue by jengeld4** [Yulife/Wanderlust-Reloaded#378]
A) Wood planks in crafting make sticks but oak planks do not display sticks as the product. Crafting still works.

B) completed gathering smeltery parts for quest, "Hot Topic". Quest disappears before completion.

**Comment by Gadgetinator** [comment]
Shooting the ender dragon with a tinkers bow can cause a server crash when the bow/arrow tries to get XP from the dragon.

Using a osmotic enchanter (from thaumic tinkerer) can cause a server/client crash.

**Comment by Yulife** [comment]
Didn't I just tell you on IRC that those got fixed in the latest version...?
