### ISSUE TITLE
TT osmotic enchanter crashing client

### ISSUE THREAD

**Issue by thcv** [Yulife/Wanderlust-Reloaded#379]
Was asked to post this here: http://pastebin.com/p1DuqiT0

**Comment by TCzelusniak** [comment]
Also crashes my server and the client, the double whammy of crahses QQ
https://pastee.org/x9zwv

**Comment by Yulife** [comment]
iirc it got fixed in the latest Thaumic Tinkerer. Will be in 2.0.0 then.
