### ISSUE TITLE
Add Fluxed Crystals

### ISSUE THREAD

**Issue by 016Nojr** [Yulife/Wanderlust-Reloaded#384]
You know you have to do it...

http://minecraft.curseforge.com/mc-mods/226074-fluxed-crystals

**Comment by 016Nojr** [comment]
@jaredlll08

**Comment by jaredlll08** [comment]
I just want to clarify... I did not ask him to do this.

**Comment by Yulife** [comment]
Sure, sure, sure!

**Comment by 016Nojr** [comment]
I legit didnt lol
