### ISSUE TITLE
Fix Uranium Cluster crafting recipes

### ISSUE THREAD

**Issue by Yulife** [Yulife/Wanderlust-Reloaded#387]

**Comment by Yulife** [comment]
Current issue: oredict wrong - @ganymedes01 looking for a fix *cough*

**Comment by ganymedes01** [comment]
Can you give me your BigReactors config file just so I can make sure my environment is the same as yours?

**Comment by Yulife** [comment]
I am using the configs you told me to use, [here](http://paste.ee/p/hKsrf)'s the full config.

**Comment by ganymedes01** [comment]
Setting B:registerYelloriumAsUranium to false seems to fix it.

**Comment by Yulife** [comment]
That deletes all of the AOBD Uranium items in the game. Didn't we talk about it and you said you are going to change the oredict name? Thanks in advance

**Comment by ganymedes01** [comment]
Yeah it deletes the uranium, but adds yellorium items (if you search you'll probably find a Yellorium Cluster).

I looked into renaming, but I can't think of a practical way of doing it... Either make uranium usable on big reactors, or completely separate it from yellorium (which is what turning that config option off does)

**Comment by Yulife** [comment]
I already added support for Yellorium items. I tried separating it from Yellorium but the config you gave me still results in the Uranium items being smelted into Yellorium.

**Comment by ganymedes01** [comment]
Uranium Clusters still smelt into yellorium ingots? i thought the cluster disappeared once you turned that config off?

**Comment by Yulife** [comment]
[This](http://puu.sh/ehUrj/25be9e491a.png) happens with [this](http://paste.ee/p/UyX9D) config.

**Comment by ganymedes01** [comment]
So change B:registerYelloriumAsUranium and the Uranium Clusters will cease to exist (since there won't be anything registered as ingotUranium). And instead Yellorium Clusters will be created, which will smelt into Yellorium Ingots

**Comment by Yulife** [comment]
But I want Uranium to exist. Some people do IC2 :P

**Comment by ganymedes01** [comment]
The ask IC2 to add uranium ingots =P
If they don't have any, what would the uranium clusters smelt into?

**Comment by Yulife** [comment]
Right.. you have a point. It does not have an ingot but Uranium 235/238 which come in "clumpy" and nugget form http://puu.sh/ei27P/0777c38b56.png

**Comment by ganymedes01** [comment]
Well AOBD was made to work with ores and ingots.
AOBD will only pick that "clumpy" uranium if it's registered in the ore dictionary as an ingot.

I can't add an exceptions for IC2 just because they don't want to register their stuff in the ore dictionary (like they also do Iridium).

**Comment by ganymedes01** [comment]
Do you use the IridumMod I made to lanse? Could just add a uranium ingot to it.

**Comment by Yulife** [comment]
No I don't. Your reasons are quite sensible - I'll disable it - thank you for the help though! ^^"

**Comment by ganymedes01** [comment]
No problem :)
Thanks for being understandable.
