### ISSUE TITLE
CTD - anvil enchanting Mekanism swords

### ISSUE THREAD

**Issue by Nocty201** [Yulife/Wanderlust-Reloaded#389]
Steps to recreate:

Spawn in an enchanted item, a plain book, a auto-disenchanter (and power source), an anvil, and a Mek sword (tested with osmium and lapis).

Disenchant item to book.

Place sword into anvil.

Attempt place book into anvil, CTD.

Tested on MS server, as well as creative SSP.

**Comment by Yulife** [comment]
Will be fixed soon.
