### ISSUE TITLE
Bees in NEI - always shows Mystical Princess to Bloody Princess

### ISSUE THREAD

**Issue by penguinsane** [Yulife/Wanderlust-Reloaded#394]
Every time you click a bee in NEI to find out it's breeding tree, it always shows the Mystical Bee -> Bloody Bee in the blood altar for Blood Magic. You have to tab over to see the actual breeding trees, etc.

Is there any way it can be changed to ... not always show that Blood Magic recipe? 99.9% of the time it's not even relevant to the one you're looking up and it's just one more thing to tab through. :(

**Comment by Yulife** [comment]
@WayofTime could we have a config in Blood Magic that ignores the bees in the plugin? I could then, with Mine/Modtweaker, implement a recipe that shows only the precise bee in NEI.

**Comment by Yulife** [comment]
Apparently it is @Arkandos' Magic Bees. May we have a config option?

**Comment by Arkandos** [comment]
For now, you can just turn off the BM module in MagicBees. All it currently adds is one bee.

**Comment by Yulife** [comment]
Alright - cheers! But wasn't it two... one blood infused one and a bound one iirc.

**Comment by Arkandos** [comment]
Hmm maybe. They don't do much. Atleast not yet.
Going to focus on new bees/fixing existing in v24.

**Comment by Yulife** [comment]
Looking forward to it. Can we expect the Thaumic Apiary @Arkandos ..? ^-^

**Comment by Arkandos** [comment]
I have a working prototype of it. I just need to get my head inside the thaumcraft api.
... and figure out how the apiary displays the info tabs on the sides.

**Comment by Yulife** [comment]
Awesome ^-^
