### ISSUE TITLE
Update Botania Aspects

### ISSUE THREAD

**Issue by Yulife** [Yulife/Wanderlust-Reloaded#396]
Blame Calvin.

**Comment by Rygor841** [comment]
Ill just put this here: 

INAP NERF THIS SHIT NOOOOOOOOOOOOW (づ｡◕‿‿◕｡)づ

**Comment by Yulife** [comment]
![200](https://cloud.githubusercontent.com/assets/8559428/5696159/cdc6a078-99c3-11e4-9f08-f1a9b3405cb0.gif)

**Comment by Yulife** [comment]
Oh my god. This took AGES. But after almost 500 lines, it is done! DONE! :laughing:

**Comment by 016Nojr** [comment]
Grattz, cat
