### ISSUE TITLE
1.2.1 NEI Not Working

### ISSUE THREAD

**Issue by Shardiru** [Yulife/Wanderlust-Reloaded#398]
Just loaded up 1.2.1 and NEI no longer shows anything at all.  With a clear search bar it shows 0/0 pages.  Tried restarting the client and no change.

**Comment by timidx3** [comment]
A friend and I are having the same issue, NEI shows 0/0 pages. Any help would be greatly apprciated!

**Comment by Yulife** [comment]
[This shall help](http://www.reddit.com/r/feedthebeast/comments/2shsjp/wanderlust_reloaded_nei_problems/)
