### ISSUE TITLE
Creating Flatworld in gamemode creative crashes the game

### ISSUE THREAD

**Issue by brynjolf** [Yulife/Wanderlust-Reloaded#399]
Survival with cheat mode on seems to work fine but if you put it in creative mode it crashes nearly instantly while trying to create the Superflat world:

http://openeye.openmods.info/crashes/3b25fe9b904482c5ff4a4e5be3e17cb3
http://openeye.openmods.info/crashes/6747bf99ec956ac7a0518749bb57769b
Wanderlust 1.2.1, nothing added or changed except enabled resource pack.

**Comment by Yulife** [comment]
http://forum.feed-the-beast.com/threads/1-7-10-wanderlust-reloaded-questing-adventure-magic-tech-hqm-over-250-quests-tabula-rasa.52737/page-90#post-880760

**Comment by brynjolf** [comment]
It is much easier solved by updating Railcraft to the RF update...

**Comment by Yulife** [comment]
Don't say that. Updating isn't easy.
