### ISSUE TITLE
Rolling machine from railcraft casues the server to crash

### ISSUE THREAD

**Issue by DoctorDrugs** [Yulife/Wanderlust-Reloaded#400]
Placing the Rolling Machine in the world instantly kills the server and the player who placed that block has minecraft fully close. When the chunk that the rolling machine is in loads for the server instantly kills the server as well.

the server and clients have fastcraft 1.13 and notenoughtitems 1.7.10-1.0.3.78 installed

crash report from the server: http://pastebin.com/BkXXa07R

**Comment by Yulife** [comment]
Jaja, will make a 1.2.2 today.
