### ISSUE TITLE
Unable to craft COmputercraft turtles (melee,mining,crafting etc)

### ISSUE THREAD

**Issue by mrdeadlocked** [Yulife/Wanderlust-Reloaded#402]
You are unable to create the specific turtle with the minetweaker script in. Remove it and you can craft them. The turtles show recipes in NEI but if you attempt to craft in table you get nothing.

**Comment by 016Nojr** [comment]
Isnt gold or iron required? If it's iron try using gold instead, if gold try iron. This has been an issue i noticed way back

**Comment by Yulife** [comment]
Use diamond tools.
