### ISSUE TITLE
Applied Energistics incompatible with current EnderIO Me Conduits

### ISSUE THREAD

**Issue by mafrasi2** [Yulife/Wanderlust-Reloaded#405]
EnderIO 2.2.6 removed compatibility with AE rv1, which makes all worlds with Me Conduits in them crash.

**Comment by magicbel** [comment]
+1 for me.
One solution is to consider before starting to edit the map ?

**Comment by mafrasi2** [comment]
Yeah, that's what I did or you could update the following according to the forum thread:
appliedenergistics2-rv1-stable-1 to appliedenergistics2-rv2-beta-7
ExtraCells-1.7.10-2.1.34bnull to ExtraCells-1.7.10-2.2.33b57
thaumicenergistics-0.8.7.2b-rv1 to thaumicenergistics-0.8.8.4b-rv2

**Comment by magicbel** [comment]
Ok, tks for the feedback !
Let's go to update it ;-)

**Comment by Chiisato** [comment]
Indeed, this is a problem. Sadly, B:removeErroringTileEntities=false in forge.cfg does NOT work as it gives another crash related to ticking update. Either manually editing the map or updating works. Any chance to get the pack updated?

**Comment by Yulife** [comment]
Fixed in 1.2.3.
