### ISSUE TITLE
How to change back to blue power marble generation 

### ISSUE THREAD

**Issue by Bramcraft** [Yulife/Wanderlust-Reloaded#409]
I have been playing the pack since it came out and didn't want to change to chisel marble(World holes , etc.). But i can't find in the config you changed to change it back, can you point me in the right direction?

**Comment by Yulife** [comment]
Sorry, what?

**Comment by Bramcraft** [comment]
In the new version of the pack, you have changed which marble spawns and I want to change it back. Which config do i need to change to but it back the way it was so all the current marble isn't deleted from world.

**Comment by Yulife** [comment]
You mean 2.0.0? I didn't change anything in 1.2.2.

**Comment by Bramcraft** [comment]
Strange i will redownload the pack guessing it missed something! Thanks anyway!
