### ISSUE TITLE
Mekanism Generators Crash Server on Placement

### ISSUE THREAD

**Issue by Oaurn** [Yulife/Wanderlust-Reloaded#411]
Were running the most recent version of Wanderlust Reloaded, aka version 1.2.2.

We are not using any of the optional mods that come with the pack, and despite this one issue the pack has been working great.    However we have run into a couple of issues trying to narrow down this problem.

Firstly, minecraft isn't generating a crash report for the server.  No idea why it isn't, but it isn't. :(

Secondly, it only seems to be happening in multiplayer and not in single player.   Whenever someone placed any of the generators from the mod, aka the bio-generator or the gas-burning generator, the server just dies.

We were able to get a single screenshot from the server terminal before it died, but that's all we have in the way of support for ya :(

http://pastebin.com/PQzaxr8q

Were gonna try and find a way to get the server to output a crash log tomorrow, hopefully we will have more info for you then.

**Comment by Yulife** [comment]
Fixed in 1.2.3.
