### ISSUE TITLE
Chat not showing in logs.

### ISSUE THREAD

**Issue by iampyrex** [Yulife/Wanderlust-Reloaded#412]
I am using cauldron 1.7.10 and the chat does not show up in the logs.  Any clue?

**Comment by Yulife** [comment]
Are you using EiraIRC?

**Comment by iampyrex** [comment]
I don't want to use IRC.  So if it is in the default pack, then yes.

**Comment by iampyrex** [comment]
I have deleted the optional mods folder.  The server is not loading EiraIRC.  I have removed EiraIRC from the client.  Chat is not logging in console or latest.log.  It also appears that Essentials and PEX is not picking it up as the name prefix and formatting is not being applied.

**Comment by Yulife** [comment]
Could you try without cauldron.

**Comment by iampyrex** [comment]
same with forge 1286

**Comment by iampyrex** [comment]
I started fresh:

unzip privatepacks^WanderlustReloaded^1_2_2^WanderlustReloadedServer.zip
java -Xmx8192M -Xms8192M -XX:PermSize=256M -jar forge-1.7.10-10.13.2.1286-universal.jar
edit eula.txt
   eula=true
save
java -Xmx8192M -Xms8192M -XX:PermSize=256M -jar forge-1.7.10-10.13.2.1286-universal.jar

Logged in
typed a message in chat - Shows up in game, no show in console or any logs.

**Comment by mathiasDJ** [comment]
To fix the plugin prefix/coloring you have to modify asielib.cfg and change enableChatTweaks and enableColor to false.

**Comment by iampyrex** [comment]
That fixed everything, except, if the client has EiraIRC, then /nick is messed up.

**Comment by Yulife** [comment]
Ahh, cheers @mathiasDJ !
