### ISSUE TITLE
Tinkers Tools, This tool has incorrect data bug (+fix ?)

### ISSUE THREAD

**Issue by Chiisato** [Yulife/Wanderlust-Reloaded#414]
*edit*

Appears wanderlust is using 2.1.2 already and the update for Iguana Tinkers Tweaks that fixes this issue hasn't been published yet or it's still broken. Commented on the original issue to see if this was fixed in 2.1.2

So, I added a vanilla modifer (Diamond/Emerald) to a tinkers tools pickaxe and now I'm stuck with a incorrect data tool. Putting it in a crafting grid does not fix it. However, the issue has been fixed in the latest version of Iguanas Tinker Tweaks. The issue can be found here, https://github.com/SlimeKnights/IguanaTweaksTConstruct/issues/64 and the commit at https://github.com/SlimeKnights/IguanaTweaksTConstruct/commit/96cce32eb16ef95e216fcdb48cd6ea5257401099

2.1.2 of Iguana Tinker Tweaks fixes this issue (among others), http://www.curse.com/mc-mods/minecraft/223248-iguanas-tinker-tweaks#t1:changes

**Comment by Chiisato** [comment]
Decided to re-open to see if anyone else can duplicate this issue running 2.1.2 Iguana Tinkers Tweaks (aka, 1.2.2 of WLR)

**Comment by Chiisato** [comment]
My hammer leveled up and naturally got a diamond modifier, now it's bugged/stuck as a incorrect data tool as well.

**Comment by 016Nojr** [comment]
Is Iguana Tweaks enabled on the server you are playing on?

**Comment by Chiisato** [comment]
Yes.

**Comment by zahuranecs** [comment]
It seems as if I have a bugged hammer as well. Didn't try any other tools yet.

**Comment by 016Nojr** [comment]
My hammer and pickaxe is bugged, not my broadsword

**Comment by mmyjona** [comment]
I got my pickaxe bugged. I'm using RR3 with iguana config file from ME^4.

**Comment by Yulife** [comment]
......What?
