### ISSUE TITLE
Chisel causing a crash

### ISSUE THREAD

**Issue by ineedbettername** [Yulife/Wanderlust-Reloaded#418]
Chisel does not interact well with a group of items that begin with the prefix RC in the config. The error was java.lang.NullPointerException: Cannot add variation in group RCAbyssalBlock for null block.

A fix for this is disabling chisel interactions with these blocks in the Chisel config, as seen below:

    B:rcAbyssalBlock=false
    B:rcBleachedBone=false
    B:rcBloodStained=false
    B:rcFrostBoundBlock=false
    B:rcInfernalStone=false
    B:rcQuarriedBlock=false
    B:rcSandyStone=false

**Comment by Yulife** [comment]
As for the fix, update to the latest Chisel 2 :P Thanks for the report, though :)
