### ISSUE TITLE
Add Thermal Dynamics

### ISSUE THREAD

**Issue by 016Nojr** [Yulife/Wanderlust-Reloaded#421]
Me want ducts! http://www.curse.com/mc-mods/minecraft/227443-thermal-dynamics#t1:other-downloads

**Comment by AforAnonymous** [comment]
I am in favor of this motion.

**Comment by Yulife** [comment]
Go ahead and dump it in your mods folder. Nothing stopping you.

**Comment by belathus** [comment]
This mod is in 2.0.0.

**Comment by 016Nojr** [comment]
Erm... is it too late to ask when 2.0.0 is getting released? ...
