### ISSUE TITLE
Various Potion ID conflicts (WLR 1.2.3)

### ISSUE THREAD

**Issue by ThePB** [Yulife/Wanderlust-Reloaded#423]
After going to fix this issue https://github.com/Yulife/Wanderlust-Reloaded/issues/406 on my client, i noticed quite a few potion id conflict with just a little bit of digging.

I've just checked Thaumic Tinkerer, Botania, Witchery, Thaumic Exploration and Blood Magic and here's the list of Conflicts i've found (prehaps some are intentional... dunno)

WI = Witchery AM2 = Ars Magica 2 BM = Blood Magic TX=Thaumic Exploration TT = Thaumic Tinkerer

32 - AM2 TX
63 - AM2 WI
86 - WI TT
87 - WI TT
89 - WI TT
90 - WI TT
100 - WI BM
101 - same
102 - same
103 - same
104 - same
105 - same
106 - same
107 - same
108 - same
109 - same
110 - same
114 - BM with itself O.o

I also mentioned Botania since it seems that 1.4-157 has a crash problem bound with its potion ids being set > 127

**Comment by belathus** [comment]
I'm curious if you were able to fix this issue. It looks to me like WLR has too many potion effects; Witchery and Ars Magica seem to be eating them for dinner.
