### ISSUE TITLE
Ender io capacitor cannot complete quest

### ISSUE THREAD

**Issue by exops91** [Yulife/Wanderlust-Reloaded#425]
With the ender io capacitor it is the wrong one in the quest book so it is a incompleteable quest as the item that's in the book is uncraftable

**Comment by Yulife** [comment]
Look at 2.0.0 changelog.

**Comment by exops91** [comment]
Where is the 2.0.0 change log as on ftb forum is only 1.2.3

**Comment by Yulife** [comment]
https://github.com/Yulife/Wanderlust-Reloaded/milestones

**Comment by exops91** [comment]
Found it will say from reading I'm liking the look of the update :) any chance you could add train craft in as its one of those mods that people who like rail tracks can make a system with real trains :) as I like making them :)
