### ISSUE TITLE
Ars Magica plants no longer drop from grass in 1.2.3

### ISSUE THREAD

**Issue by Blacksm1th** [Yulife/Wanderlust-Reloaded#426]
Hoeing unhydrated grass used to drop Ars Magica plants (Aum, Tarma, Cerublossom). In the latest update they do not.

**Comment by Blacksm1th** [comment]
Per AM2 patch notes at http://qorconcept.com/mc/patchnotes/1.4.0.007_patch_notes.txt, "-AM Flowers no longer drop from tall grass."

**Comment by Yulife** [comment]
Oh, lol.
