### ISSUE TITLE
for 2.0.0 could iguana tweaks be more harder

### ISSUE THREAD

**Issue by exops91** [Yulife/Wanderlust-Reloaded#428]
was feeling iguana tweaks at the moment are way to easy to progress through where the normal tweaks you need to work the pic first to then get it able to mine better stuff then you can progress to the next stage which i find better as then it slows the progress on the later quest a but so then people can focus on getting food and other ones done more first then they can move onto getting the better tools to then move onto the other more higher needs mods where more higher tier resources are needed and then once you get to the higer tiers you then get the atomic dissembler which then make all tools obsolete :P

inputing my opinion on this as how i feel with the state of the tools at the moment also with the tinkers do a poll or a post on peoples best tools and items and do a quest tab  specific to tinkers instead of the one in the first area and the same for the AE as the iron gear box is a research so i find it needs removing as then people can then make tools and have quests showing how to progress iguana but also then at the end have tools that are unique to each person and makes you feel like you have actually done something to get that tool instead of getting it moving to other items and just throwing them away

**Comment by Waisse** [comment]
Default config is fine, I don't see why it was nerfed.

**Comment by exops91** [comment]
Iguana tweaks was made so to get to mining coal you needed to use your pic first on cobble to get the mining level up to then mine it then you could then be able to mine copper which you then replace the head with copper mine items that you did before then they levels and you get to mine iron and it goes from that which is why I think also the tools sometimes say incorrect data and you can't sort them out but if the original tweaks where in then it might sort it out and not make tools obsolete fast but make them personal and make you want to keep them

**Comment by Waisse** [comment]
Please use punctuation it's unreadable.

**Comment by exops91** [comment]
Please suck my nob you fag is that more your thing ?

**Comment by belathus** [comment]
Whoa. None of that here.

Also, I have no intention of making Iguana Tweaks harder at this time.
