### ISSUE TITLE
Cannot complete Initium -> Combat System quest in 2.0.0

### ISSUE THREAD

**Issue by CorenMajere** [Yulife/Wanderlust-Reloaded#431]
The stone dagger does not appear to be craftable in 2.0.0.  Neither the default recipe for the mod (cobblestone above a stick), nor the recipe displayed in NEI (cobblestone diagonally above wooden spear) work.  This prevents completion of the Combat System quest in Initium.

**Comment by Waisse** [comment]
I suggest reworking this quest and make the player only craft a tinkers' defense shield instead of all those weapons.

**Comment by belathus** [comment]
Until a fix is released, you can get around this issue by using the colored cobblestone from Extra Utilities.
