### ISSUE TITLE
Mine & Blade fixes

### ISSUE THREAD

**Issue by Waisse** [Yulife/Wanderlust-Reloaded#433]
Can't use the quiver with ticon arrows.
Can't place a ticon shortbow in the Mine & Blade weapon slot.
Several ticon "tools" like the hammer can't be placed in the Mine & Blade weapon slot (would be more a qol fix than a bug for that one).

Ticon weapons with flux modifier aren't recharged by ender io wireless charger if they are in the Mine & Blade slots.

**Comment by exops91** [comment]
that is to do with ticon doesnt like mine blade as u cant level weapons up in the mine blade ui and comes to ticon arrows they wont work in the quiver as that only accepts mineblade arrows or vanilla as tcon ones are very different to vanilla

**Comment by Waisse** [comment]
That was exactly what I said so uh ... thanks ? But you said we can't even level up ticon weapons in Mine & Blade slots, wow that suck.

**Comment by Yulife** [comment]
I don't code those mods. Wrong repo.
