### ISSUE TITLE
Server lagging then hanging

### ISSUE THREAD

**Issue by BlackD0** [Yulife/Wanderlust-Reloaded#437]
I have been hosting a Wanderlust Reloaded 2.0.0 server for about a week now, and nothing was wrong so far. That is until a '"Silently" catching entity tracking error' started popping up yesterday (see pastebin for my latest try to connect to my server). 

It's been causing a whole lot of lag, which pretty much makes the game unplayable. As soon as I try to go to the Nether (which happened when I joined in the pasted log) the server just stops responding. I manually stopped the server at the end, for it wouldn't respond for atleast 5 minutes. My server is hosted at nodecraft.com, I have the star package found here: https://nodecraft.com/game-servers/minecraft

The logs:
http://pastebin.com/CF6HCaJU

To me it seems like something is wrong with the Hellhound entities from Witchery, but it might aswell be my ender pump making the server go batshit crazy. I read something that when an ender pump is too close to a nether fortress it might cause similair issues.

**Comment by belathus** [comment]
You may Be right about the ender pump. Sounds similar to this issue: https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/issues/161#issuecomment-72996794

**Comment by BlackD0** [comment]
The problem is, though, I can't get into the nether. If I do the server just... stops

**Comment by belathus** [comment]
Can you access it by putting the server in peaceful?

**Comment by BlackD0** [comment]
If I try to put it on peaceful mode, it still loads enemies. It keeps me stuck in limbo when I try to load up the nether. Image: http://i.imgur.com/Hnj19pr.png

**Comment by belathus** [comment]
Can you run CoFH killall on the server? Not that you should have to on peaceful... also, you could try using World Edit to remove the entities/pump.

**Comment by BlackD0** [comment]
We've already started a new world, no biggie. Thanks for the help anyway. We've disabled the Ender-thermic Pump alltogether :p
