### ISSUE TITLE
Is there any way to stop Forge asking permission to load a world? 

### ISSUE THREAD

**Issue by Krystallus** [Yulife/Wanderlust-Reloaded#446]
Is there any way to stop Forge asking permission to load a world? I can't use the old world on the server because of the update, because Forge wants permission to load it with missing mods.

**Comment by belathus** [comment]
Can't you just type /fml confirm?

**Comment by Krystallus** [comment]
That worked, thanks. By the way, the FTB forums will not let me reply to the conversation about the server being put up somewhere, either of the options you listed would be great.
